import { Router } from 'express'
import { authenticate } from '../middleware/auth'
import Session from '../models/Session'
import User from '../models/User'
import ARIAProfile from '../models/ARIAProfile'

const router = Router()

router.get('/overview', authenticate, async (req, res, next) => {
  try {
    const user = req.user!
    const resData = {
      accuracy7d: user.accuracy || 0, accuracy30d: user.accuracy || 0, accuracy90d: user.accuracy || 0,
      questionsToday: 0, questionsWeek: 0,
      studyHoursToday: 0, studyHoursWeek: 0,
      accuracy: user.accuracy || 0,
      streakCurrent: user.streak || 0, streakLongest: user.longestStreak || 0,
      projectedPercentile: user.projectedPercentile || 0,
      weakTopics: user.weakTopics?.slice(0, 5) || [],
      flashcardsDue: 0
    }
    res.json(resData)
  } catch (err) { next(err) }
})

router.get('/performance-trend', authenticate, async (req, res, next) => {
  try {
    res.json({ data: [] })
  } catch (err) { next(err) }
})

router.get('/subject-breakdown', authenticate, async (req, res, next) => {
  try {
    res.json([])
  } catch (err) { next(err) }
})

router.get('/error-analysis', authenticate, async (req, res, next) => {
  try {
    const profile = await ARIAProfile.findOne({ userId: req.user?._id })
    res.json({ patterns: profile?.errorDNA || [] })
  } catch (err) { next(err) }
})

router.get('/session-history', authenticate, async (req, res, next) => {
  try {
    const { page = 1, limit = 10 } = req.query
    const sessions = await Session.find({ userId: req.user?._id })
      .sort({ createdAt: -1 })
      .skip((Number(page)-1)*Number(limit)).limit(Number(limit))
    res.json(sessions)
  } catch (err) { next(err) }
})

router.post('/session/start', authenticate, async (req, res, next) => {
  try {
    const { subject, topic, plannedMinutes } = req.body
    const session = await Session.create({
      userId: req.user?._id,
      subject, topic, plannedMinutes,
      status: 'active',
      startedAt: new Date()
    })
    res.json({ sessionId: session._id })
  } catch (err) { next(err) }
})

router.patch('/session/:id/end', authenticate, async (req, res, next) => {
  try {
    const { actualMinutes, questionsAttempted, questionsCorrect } = req.body
    const session = await Session.findById(req.params.id)
    if (!session) return res.status(404).json({ error: 'Session not found' })

    session.actualMinutes = actualMinutes
    session.questionsAttempted = questionsAttempted
    session.questionsCorrect = questionsCorrect
    session.status = 'completed'
    session.completedAt = new Date()
    await session.save()

    const user = await User.findById(req.user?._id)
    if (user) {
      user.totalStudyMinutes += actualMinutes
      await user.save()
    }

    res.json({ session, insights: 'Great session!' })
  } catch (err) { next(err) }
})

router.get('/weekly-report', authenticate, async (req, res, next) => {
  try {
    res.json({ summary: 'Weekly report data generated by ARIA' })
  } catch (err) { next(err) }
})

export default router
